# -*- coding: utf-8 -*-
"""Copy of ASSIGNMENTS.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iPM9B0ZepO2Q4Qclgjwbuoc_A3cphB-3

Week 1 Assignment1
"""

a=int(input("Enter first number: "))
b=int(input("Enter second numbers: "))
c=a
a=b
b=c
print(a)
print(b)

"""Week 1 Assignment 2"""

a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
c=int(input("Enter a number: "))
if a>b>c:
  print(a)
elif b>a>c:
  print(b)
else:
  print(c)

a=int(input("Enter a number: "))
b=int(input("Enter a number: "))
c=int(input("Enter a number: "))
if a<b<c:
  print(a)
elif b<a<c:
  print(b)
else:
  print(c)

"""Week 2 Assignment 1"""

a=str(input("Enter a two digit number: "))
if a[0]>a[1]:
  print(a[0])
else:
  print(a[1])

"""Week 2 Assignment 2"""

a=str(input("Enter a number"))
if a[0]*a[0]*a[0]+a[1]*a[1]*a[1]+a[2]*a[2]*a[2]==str(a):
  print("it is an amstrong number: ")
else:
  print("it is not an amstrong number: ")

"""Week 2 Assignment 3"""

a=str(input("enter a number: "))
i=1
for i in a:
  a[i]=a[-i]
  i+=1
print(a)