# -*- coding: utf-8 -*-
"""w1a1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YkYU4RZzWIaXlECP5yWaKuIEC3jqG-Qv
"""

a=int(input("Enter first number: "))
b=int(input("Enter second numbers: "))
c=a
a=b
b=c
print(a)
print(b)